publishDir: docs

baseURL: https://blog.ooopiz.com/
title: 馬丁沒有派對
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-4XSTL9TGTE
disqusShortname: blog-ooopiz


minify:
  disableXML: true
  # minifyOutput: true


menu:
  main:
    - name: Home
      weight: 10
      identifier: home
      url: /
    - name: Archives
      weight: 20
      identifier: archives
      url: /post/
    - name: Tags
      weight: 30
      identifier: tags
      url: /tags/
    #- name: Categories
    #  weight: 40
    #  url: /categories/
    - name: About
      weight: 50
      identifier: about
      url: /about/


params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: 馬丁沒有派對
  description: "我把青春都寫在blog上了 \U0001F61C\U0001F61C"
  keywords: [devops, 運維, 後端]
  #author: me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # auto, dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  ShareButtons: ["twitter", "linkedin", "reddit", "facebook", "telegram"]
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  googleAdsense: ca-pub-3680083267042451

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: /favicon.ico
    favicon16x16: /favicon-16x16.png
    favicon32x32: /favicon-32x32.png
    apple_touch_icon: /apple-touch-icon.png
    safari_pinned_tab: /safari-pinned-tab.svg

  label:
    text: "馬丁沒有派對"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    #- name: github
    #  url: "https://github.com/ooopiz"

